/**
 * Admin Operations Example
 * 
 * Demonstrates Phase 4 admin features:
 * - Initialize pool
 * - Set and lock verification key
 * - Two-step authority transfer
 * - Pause/unpause pool
 */

import { Connection, PublicKey, Keypair } from '@solana/web3.js';
import { Wallet } from '@coral-xyz/anchor';
import * as fs from 'fs';

import {
  PsolProgram,
  vkeyJsonToOnChain,
  deriveAllPoolPDAs,
  PSOL_CONSTANTS,
  PsolError,
  PsolErrorCode,
} from '@psol/sdk';

// Configuration
const RPC_URL = 'https://api.devnet.solana.com';

async function main() {
  console.log('=== pSol Admin Operations Demo ===\n');

  // Setup
  const connection = new Connection(RPC_URL, 'confirmed');
  const adminKeypair = Keypair.generate();
  const adminWallet = new Wallet(adminKeypair);
  const program = new PsolProgram(connection, adminWallet);

  // Create a test token mint (in production, use existing mint)
  const tokenMint = Keypair.generate().publicKey;

  console.log('Admin:', adminWallet.publicKey.toBase58());
  console.log('Token Mint:', tokenMint.toBase58());

  // 1. Initialize Pool
  console.log('\n--- 1. Initialize Pool ---');
  try {
    const result = await program.initializePool(tokenMint, {
      treeDepth: PSOL_CONSTANTS.DEFAULT_TREE_DEPTH, // 20
      rootHistorySize: PSOL_CONSTANTS.DEFAULT_ROOT_HISTORY, // 100
    });
    console.log('Pool initialized:', result.signature);

    const pdas = deriveAllPoolPDAs(tokenMint);
    console.log('Pool Config:', pdas.poolConfig[0].toBase58());
    console.log('Vault:', pdas.vault[0].toBase58());
    console.log('Merkle Tree:', pdas.merkleTree[0].toBase58());
    console.log('Verification Key:', pdas.verificationKey[0].toBase58());
  } catch (error) {
    console.error('Failed to initialize pool:', error);
    return;
  }

  // 2. Set Verification Key
  console.log('\n--- 2. Set Verification Key ---');
  try {
    // Load VK from file (generated by snarkjs)
    const vkeyJson = JSON.parse(fs.readFileSync('./verification_key.json', 'utf-8'));
    const vk = vkeyJsonToOnChain(vkeyJson);

    const result = await program.setVerificationKey(tokenMint, vk);
    console.log('VK set:', result.signature);
    console.log('IC points:', vk.ic.length);
  } catch (error) {
    console.error('Failed to set VK:', error);
    // Continue demo with other operations
  }

  // 3. Lock Verification Key (WARNING: Irreversible!)
  console.log('\n--- 3. Lock Verification Key ---');
  console.log('⚠️  WARNING: This action is PERMANENT and cannot be undone!');
  console.log('In production, only lock after thorough testing.');
  
  // Uncomment to actually lock:
  // try {
  //   const result = await program.lockVerificationKey(tokenMint);
  //   console.log('VK locked:', result.signature);
  // } catch (error) {
  //   console.error('Failed to lock VK:', error);
  // }

  // 4. Two-Step Authority Transfer
  console.log('\n--- 4. Two-Step Authority Transfer ---');
  const newAdminKeypair = Keypair.generate();
  const newAdminWallet = new Wallet(newAdminKeypair);
  const newProgram = new PsolProgram(connection, newAdminWallet);

  console.log('New Admin:', newAdminWallet.publicKey.toBase58());

  // Step 1: Current admin initiates transfer
  try {
    console.log('Step 1: Initiating transfer...');
    const result = await program.initiateAuthorityTransfer(
      tokenMint,
      newAdminWallet.publicKey
    );
    console.log('Transfer initiated:', result.signature);
  } catch (error) {
    console.error('Failed to initiate transfer:', error);
    return;
  }

  // Optional: Cancel transfer if wrong address
  // try {
  //   console.log('Cancelling transfer...');
  //   const result = await program.cancelAuthorityTransfer(tokenMint);
  //   console.log('Transfer cancelled:', result.signature);
  // } catch (error) {
  //   console.error('Failed to cancel transfer:', error);
  // }

  // Step 2: New admin accepts transfer
  try {
    console.log('Step 2: Accepting transfer...');
    const result = await newProgram.acceptAuthorityTransfer(tokenMint);
    console.log('Transfer accepted:', result.signature);
    console.log('New authority is now:', newAdminWallet.publicKey.toBase58());
  } catch (error) {
    console.error('Failed to accept transfer:', error);
  }

  // 5. Pause Pool
  console.log('\n--- 5. Pause Pool ---');
  try {
    const result = await newProgram.pausePool(tokenMint);
    console.log('Pool paused:', result.signature);
  } catch (error) {
    console.error('Failed to pause pool:', error);
  }

  // 6. Unpause Pool
  console.log('\n--- 6. Unpause Pool ---');
  try {
    const result = await newProgram.unpausePool(tokenMint);
    console.log('Pool unpaused:', result.signature);
  } catch (error) {
    console.error('Failed to unpause pool:', error);
  }

  // 7. Fetch Pool Status
  console.log('\n--- 7. Final Pool Status ---');
  try {
    const pool = await newProgram.fetchPoolConfig(tokenMint);
    if (pool) {
      console.log('Authority:', pool.authority.toBase58());
      console.log('Pending Authority:', pool.pendingAuthority.toBase58());
      console.log('Is Paused:', pool.isPaused);
      console.log('VK Configured:', pool.vkConfigured);
      console.log('VK Locked:', pool.vkLocked);
      console.log('Total Deposits:', pool.totalDeposits.toString());
      console.log('Version:', pool.version);
    }
  } catch (error) {
    console.error('Failed to fetch pool:', error);
  }

  console.log('\n=== Admin Demo Complete ===');
}

main().catch(console.error);
